---
- name: Copy cgit config files
  ansible.builtin.template:
    src: "./tasks/templates/cgit/{{ item }}.j2"
    dest: "{{ apps_dir }}/cgit/config/{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0644"
  with_items:
    - "footer.html"
    - "custom"
    - "style.css"

- name: Start cgit
  ansible.builtin.command:
    cmd: "docker compose up -d cgit"
    chdir: "{{ apps_dir }}"
