---
- name: Update packages
  apk:
    update_cache: true
    upgrade: true

- name: Install system packages
  apk:
    name:
      - tzdata
    state: present

- name: Install packages
  apk:
    name: "{{ vps_packages }}"
    state: present
