---
- name: Update packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 86400
    upgrade: true

- name: Install packages
  ansible.builtin.apt:
    name:
      - curl
      - git
      - make
      - sudo
      - vim
      - lsblk
      - gnupg
      - software-properties-common
      - python3
      - jq
      - unzip
      - ca-certificates
    state: present
