---
- name: Update packages
  community.general.apk:
    update_cache: true
    upgrade: true

- name: Install packages
  community.general.apk:
    name:
      - alpine-base
      - ca-certificates
      - curl
      - git
      - jq
      - make
      - logrotate
      - lsblk
      - openssh-server
      - python3
      - sudo
      - tzdata
      - vim
    state: present
