name: Build docker images
on:
  push:
    branches: [master]

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      caddy: ${{ steps.filter.outputs.caddy }}
      cgit: ${{ steps.filter.outputs.cgit }}
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Paths filter
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            caddy:
              - 'apps/caddy/**'
            cgit:
              - 'apps/cgit/**'

  build:
    runs-on: ubuntu-latest
    needs: filter
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Declare short commit SHA
        run: |
          echo "sha=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"

      - name: Build and push Caddy
        if: needs.filter.outputs.caddy == 'true'
        uses: docker/build-push-action@v5
        with:
          context: apps/caddy
          file: apps/caddy/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/caddy:${{ env.sha }}
            ghcr.io/${{ github.actor }}/caddy:latest

      - name: Build and push cgit
        if: steps.filter.outputs.cgit == 'true'
        uses: docker/build-push-action@v5
        with:
          context: apps/cgit
          file: apps/cgit/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/cgit:${{ env.sha }}
            ghcr.io/${{ github.actor }}/cgit:latest

      - name: Build and push cgit-nginx
        if: steps.filter.outputs.cgit == 'true'
        uses: docker/build-push-action@v5
        with:
          context: apps/cgit
          file: apps/cgit/Dockerfile.nginx
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/cgit:nginx-${{ env.sha }}
