name: Build docker images
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Paths filter
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            caddy:
              - 'apps/caddy/**'
            cgit:
              - 'apps/cgit/**'

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Caddy
        if: steps.filter.outputs.caddy == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/caddy/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/caddy:2.7.5-alpine
            ghcr.io/${{ github.actor }}/caddy:latest

      - name: Build and push cgit
        if: steps.filter.outputs.cgit == 'true'
        uses: docker/build-push-action@v5
        with:
          context: apps/cgit
          file: apps/cgit/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/cgit:1.2.3-alpine
            ghcr.io/${{ github.actor }}/cgit:latest

      - name: Build and push cgit-nginx
        if: steps.filter.outputs.cgit == 'true'
        uses: docker/build-push-action@v5
        with:
          context: apps/cgit
          file: apps/cgit/Dockerfile.nginx
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/cgit:1.2.3-alpine-nginx
